/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fieldSystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lightness kabajunes
 */
public class Coordinatorsupervisor extends javax.swing.JFrame {

    /**
     * Creates new form Coordinatorsupervisor
     */
    public Coordinatorsupervisor() {
        initComponents();
        filltable();
    }
    public void filltable()
    {
        try {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/fieldsystem","root","");
            String sql="SELECT * FROM supervisor";
            PreparedStatement pst;
            pst=conn.prepareStatement(sql);
            DefaultTableModel model=(DefaultTableModel) Table1.getModel();
            model.setRowCount(0);
            ResultSet rs;
            rs=pst.executeQuery();
            while(rs.next())
            {
                Object[] content={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                model.addRow(content);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        RegNo = new javax.swing.JTextField();
        btnSubmit2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        surname1 = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnSubmit3 = new javax.swing.JButton();

        jLabel3.setText("REGISTRATION NUMBER:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(51, 0, 51));
        jPanel3.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" REGISTER SUPERVISOR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(34, 24, 500, 40);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(160, 60, 560, 80);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 0, 890, 190);

        jPanel2.setBackground(new java.awt.Color(255, 153, 204));
        jPanel2.setLayout(null);

        jTabbedPane1.setForeground(new java.awt.Color(51, 0, 51));

        jPanel4.setBackground(new java.awt.Color(255, 153, 204));
        jPanel4.setLayout(null);

        jLabel2.setText("PHONE NO :");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(30, 230, 59, 14);

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel4.add(phone);
        phone.setBounds(20, 260, 190, 30);

        RegNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegNoActionPerformed(evt);
            }
        });
        jPanel4.add(RegNo);
        RegNo.setBounds(20, 50, 190, 30);

        btnSubmit2.setBackground(new java.awt.Color(51, 0, 51));
        btnSubmit2.setForeground(new java.awt.Color(255, 102, 204));
        btnSubmit2.setText("SUBMIT");
        btnSubmit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnSubmit2);
        btnSubmit2.setBounds(20, 390, 110, 40);

        jLabel4.setText("SURNAME  :");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 80, 120, 50);

        surname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surname1ActionPerformed(evt);
            }
        });
        jPanel4.add(surname1);
        surname1.setBounds(20, 120, 190, 30);

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel4.add(firstname);
        firstname.setBounds(20, 190, 180, 30);

        jLabel5.setText("FIRST NAME    :");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 150, 120, 50);

        jLabel6.setText("REG NO:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(30, 10, 60, 30);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reg No", "First Name", "Surname", "Password", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(240, 40, 550, 300);
        jPanel4.add(jLabel7);
        jLabel7.setBounds(10, 310, 220, 40);

        btnSubmit3.setBackground(new java.awt.Color(51, 0, 51));
        btnSubmit3.setForeground(new java.awt.Color(255, 102, 204));
        btnSubmit3.setText("ASSIGN");
        btnSubmit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit3ActionPerformed(evt);
            }
        });
        jPanel4.add(btnSubmit3);
        btnSubmit3.setBounds(170, 390, 110, 40);

        jTabbedPane1.addTab("REGISTER SUPERVISOR", jPanel4);

        jPanel2.add(jTabbedPane1);
        jTabbedPane1.setBounds(70, 80, 800, 570);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 190, 960, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void surname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surname1ActionPerformed

    private void btnSubmit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit2ActionPerformed
        Connection con=null;
        PreparedStatement pst=null;
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost/fieldsystem","root","");
            String sql="INSERT INTO Supervisor(RegNo,FirstName,Surname,Password,Phone) VALUES(?,?,?,?,?)";
            pst=con.prepareStatement(sql);
            pst.setString(1,RegNo.getText());
            pst.setString(2,firstname.getText());
            pst.setString(3,surname1.getText());
            pst.setString(4,surname1.getText());
            pst.setString(5,phone.getText());
            pst.executeUpdate();
            if(!"".equals(surname1.getText())){jLabel7.setText("Password will be"+" "+surname1.getText());}

            JOptionPane.showMessageDialog(null,"SUCESSFULLY REGISTERED");
            filltable();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_btnSubmit2ActionPerformed

    private void RegNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegNoActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void btnSubmit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit3ActionPerformed
        // TODO add your handling code here:
        Assigning myassign=new Assigning();
        myassign.setVisible(true);
    }//GEN-LAST:event_btnSubmit3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coordinatorsupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coordinatorsupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coordinatorsupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coordinatorsupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coordinatorsupervisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RegNo;
    private javax.swing.JTable Table1;
    private javax.swing.JButton btnSubmit2;
    private javax.swing.JButton btnSubmit3;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField surname1;
    // End of variables declaration//GEN-END:variables
}
